translate_task:
  description: >
    Translate {sentence} from English to Japanese without making mistakes.
  expected_output: >
    A well formatted translation from English to Japanese.
  agent: translator_agent

retranslate_task:
  description: >
    Translate {sentence} from Japanese to Korean without making mistakes.
  expected_output: >
    A well formatted translation from ItaliJapanesean to Korean.
  agent: translator_agent

count_task:
  description: >
    Count the amount of letters in a sentence.
  expected_output: >
    The number of letters in the sentence.
  agent: counter_agent
